"""create groups table

Revision ID: 90ed01ec2405
Revises: 481b591f1d0f
Create Date: 2025-04-09 12:39:41.335200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ed01ec2405'
down_revision: Union[str, None] = '481b591f1d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('group_name', sa.String(length=40), nullable=False))
    op.create_foreign_key(None, 'users', 'groups', ['group_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_name')
    op.drop_table('groups')
    # ### end Alembic commands ###
